services:
  # Game Server
  - type: web
    name: gangs-online-server
    runtime: node
    region: singapore
    plan: free
    rootDir: packages/server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 2567
