services:
  # Game Server
  - type: web
    name: gangs-online-server
    runtime: node
    region: singapore
    plan: free
    buildCommand: cd packages/shared && npm install && npm run build && cd ../server && npm install
    startCommand: cd packages/server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 2567
